USE [ExamenRAD]
GO

/****** Object:  StoredProcedure [dbo].[SP_TRANSACCION]    Script Date: 1/11/2022 21:32:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<GISELA GOMES,>
-- Create date: < ,>
-- Description:	<TRANSACCIONES DE LAS TABLAS,>
-- =============================================
CREATE PROCEDURE  [dbo].[SP_TRANSACCION]
	
	@OPCION INT,
	@USUARIO VARCHAR(15),
	@CLAVE VARCHAR(15),
	@NOMBRE VARCHAR(50),
	@NIVELACCESO INT,
	@FECHA DATE,
	@ACTIVO BIT 

	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF @OPCION = 1

INSERT INTO USUARIOS(USUARIO, CLAVE, NOMBRE, NIVELACCESO,FECHA, ACTIVO)
VALUES(@USUARIO, @CLAVE, @NOMBRE,@NIVELACCESO , @FECHA, @ACTIVO)

IF @OPCION = 2

UPDATE USUARIOS 
SET  CLAVE = @CLAVE, NOMBRE = @NOMBRE, NIVELACCESO = @NIVELACCESO, FECHA = @FECHA, ACTIVO = @ACTIVO
WHERE USUARIO = @USUARIO

IF @OPCION = 3

DELETE FROM USUARIOS
WHERE  USUARIO = @USUARIO


IF @OPCION = 4
SELECT * FROM USUARIOS
WHERE  USUARIO = @USUARIO

IF @OPCION = 5
SELECT * FROM USUARIOS



END
GO

